-
  hosts: all

  tasks:
    - name: add nodejs repo
      apt_repository: repo='ppa:chris-lea/node.js' state=present

    - name: update apt cache
      apt: update_cache=yes

    - name: install dependencies
      apt: pkg={{ item }} state=latest
      with_items:
      - nodejs
      - phantomjs
      - g++
      - build-essential

    - npm: name={{ item }} state=latest global=yes
      with_items:
      - gulp
      - bower
